# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 537e03419d8a4855eb528248745e82a500a65312b03a3ce2c0e334831213487984b2a3e7468619cf254800642b5454baf54083b3164143a50d91449ccdba3801

test:
  secret_key_base: c1e85d7f6e923c5a3982e2628eb2dd4801fe17e522e992b6ce208cb288c46c7a9b862a78ec833333945ed5c1e483c049f67b4f01b4723f47c376a6a64ff8f6d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
